workflows:
  version: 2.1
  azure-infra-provision:
    jobs:
      - generate-tfc-token
version: 2.1
executors:
  tf-executor:
    docker:
      - image: hashicorp/terraform
    working_directory: /tmp
  vault-executor:
    docker:
      - image: hashicorp/vault
    working_directory: /home/vault
jobs:
  generate-tfc-token:
    executor: vault-executor
    steps:
      - run: mkdir workspace
      - run:
          name: "Import TFC API Token from Vault"
          command: |
            pwd
            vault -version
            vault kv get secret/azure/environment
#      - persist_to_workspace:
#          root: workspace
#          paths:
#            - ids-output.json