workflows:
  version: 2.1
  azure-infra-provision:
    jobs:
      - generate-tfc-token
version: 2.1
executors:
  tf-executor:
    docker:
      - image: hashicorp/terraform
    working_directory: /tmp
  vault-executor:
    docker:
      - image: hashicorp/vault
    working_directory: /home/vault
jobs:
  generate-tfc-token:
    executor: vault-executor
    steps:
      - run: mkdir workspace
      - run:
          name: "Import TFC API Token from Vault"
          command: |
            pwd
            vault -version
            export TFC_TOKEN=$(vault read -format json tfc/creds/ci-user | jq -r '.data.token')

            echo "{" > workspace/ids-output.json
            echo "  \"tfc_token\": \"${TFC_TOKEN}\"," >> workspace/ids-output.json
            echo "}" >> workspace/ids-output.json

            cat workspace/ids-output.json
#      - persist_to_workspace:
#          root: workspace
#          paths:
#            - ids-output.json