workflows:
  version: 2.1
  my-workflow:
    jobs:
      - generate-tfc-token
version: 2.1
executors:
  tf-executor:
    docker:
      - image: hashicorp/terraform
  vault-executor:
    docker:
      - image: hashicorp/vault
jobs:
  generate-tfc-token:
    executor: vault-executor
    steps:
      - run: mkdir -p workspace
      - run:
          name: "Import TFC API Token from Vault"
          command: |
            vault -version
      - persist_to_workspace:
          root: workspace
          paths:
            - ids-output.json