workflows:
  version: 2.1
  azure-infra-provision:
    jobs:
      - generate-tfc-token
      - terraform-test:
          requires:
            - generate-tfc-token
version: 2.1
executors:
  tf-executor:
    docker:
      - image: hashicorp/terraform
    working_directory: /tmp
  vault-executor:
    docker:
      - image: hashicorp/vault
    working_directory: /home/vault
jobs:
  generate-tfc-token:
    executor: vault-executor
    steps:
      - run: mkdir workspace
      - run:
          name: "Import TFC API Token from Vault"
          command: |
            pwd
            vault -version
            apk add jq
            export TFC_TOKEN=$(vault read -format json tfc/creds/ci-user | jq -r '.data.token')

            echo "{" > workspace/tf-token-output.json
            echo "  \"tfc_token\": \"${TFC_TOKEN}\"," >> workspace/tf-token-output.json
            echo "}" >> workspace/tf-token-output.json

            cat workspace/tf-token-output.json
      - persist_to_workspace:
          root: workspace
          paths:
            - tf-token-output.json
  terraform-test:
    executor: tf-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: "Terraform Test"
          command: |
            pwd
            apk install git
            git clone https://github.com/tkaburagi/tf-vault-github-actions-src
            terraform -version
            ls -ltrR
            terraform fmt -diff=true
            terraform init
            terraform validate