workflows:
  version: 2.1
  azure-infra-provision:
    jobs:
      - terraform-test
      - generate-tfc-token:
          requires:
            - terraform-test
      - generate-azure-secret:
          requires:
            - generate-tfc-token
version: 2.1
executors:
  tf-executor:
    docker:
      - image: hashicorp/terraform
    working_directory: /tmp
  vault-executor:
    docker:
      - image: hashicorp/vault
    working_directory: /home/vault
jobs:
  terraform-test:
    executor: tf-executor
    steps:
      - run:
          name: "Terraform Test"
          command: |
            pwd
            apk add git
            git clone https://github.com/tkaburagi/tf-vault-github-actions-src
            terraform -version
            ls -ltrR
            cd tf-vault-github-actions-src
            terraform fmt -diff=true
            terraform init
            terraform validate
  generate-tfc-token:
    executor: vault-executor
    steps:
      - run: mkdir workspace
      - run:
          name: "Import TFC API Token from Vault"
          command: |
            pwd
            vault -version
            apk add jq
            export TFC_TOKEN=$(vault read -format json tfc/creds/ci-user | jq -r '.data.token')

            echo "{" > workspace/tf-token-output.json
            echo "  \"tfc_token\": \"${TFC_TOKEN}\"," >> workspace/tf-token-output.json
            echo "}" >> workspace/tf-token-output.json

            cat workspace/tf-token-output.json
      - persist_to_workspace:
          root: workspace
          paths:
            - tf-token-output.json
  generate-azure-secret:
    executor: vault-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: "Import Azure Secrets from Vault"
          command: |
            pwd
            apk add jq
            vault read -format json azure/creds/contributor > client-creds.json
            vault kv get -format json secret/azure/environment > env-creds.json

            export ARM_CLIENT_ID=$(cat client-creds.json | jq -r '.data.client_id')
            export ARM_CLIENT_SECRET=$(cat client-creds.json | jq -r '.data.client_secret')
            export ARM_SUBSCRIPTION_ID=$(cat env-creds.json | jq -r '.data.data.subscription_id')
            export ARM_TENANT_ID=$(cat env-creds.json | jq -r '.data.data.tenant_id')

            echo ${ARM_CLIENT_ID}
            echo ${ARM_SUBSCRIPTION_ID}

            ls -ltrR
      - persist_to_workspace:
          root: workspace
          paths:
            - env-creds.json
            - client-creds.json